name = "formatdisc-hr"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_APP_URL = "https://www.formatdisc.hr"

[[routes]]
pattern = "www.formatdisc.hr/*"
zone_name = "formatdisc.hr"
